import type { BlogPost, BlogPostSummary, BlogContentBlock } from '@/types';

const SHARED_BLOCKS: Record<string, BlogContentBlock[]> = {};

const POSTS: Record<string, BlogPost> = {
  'jak-zlecic-obraz-przewodnik': {
    id: 'fallback-1',
    slug: 'jak-zlecic-obraz-przewodnik',
    title: 'Jak zlecić obraz - kompletny przewodnik krok po kroku',
    excerpt: 'Od pomysłu do realizacji: opisz zlecenie, dodaj inspiracje, wybierz artystę i odbierz obraz. Przewodnik po całym procesie zlecania obrazu na zamówienie.',
    content: SHARED_BLOCKS['jak-zlecic-obraz-przewodnik'] ?? [
      { type: 'paragraph', text: 'Zlecanie obrazu na zamówienie może wydawać się skomplikowane, ale platforma Artiors upraszcza cały proces do kilku jasnych kroków. W tym przewodniku przeprowadzimy Cię przez każdy etap - od sformułowania pomysłu, przez publikację zlecenia, po odbiór gotowego obrazu.' },
      { type: 'heading', level: 2, text: 'Krok 1: Opisz obraz' },
      { type: 'paragraph', text: 'Podaj styl, wymiary, paletę kolorów, nastrój i pomieszczenie, w którym obraz będzie wisiał. Im precyzyjniejszy opis, tym lepsze oferty otrzymasz od artystów.' },
      { type: 'heading', level: 2, text: 'Krok 2: Dodaj inspiracje' },
      { type: 'paragraph', text: 'Załącz zdjęcia wnętrza, palety i obrazów referencyjnych. Inspiracje pomagają artystom zrozumieć Twoją wizję i składają dokładniejsze oferty.' },
      { type: 'heading', level: 2, text: 'Krok 3: Ustaw budżet i termin' },
      { type: 'paragraph', text: 'Podaj zakres cenowy i datę, do której obraz ma być gotowy. Realistyczny termin zazwyczaj oznacza lepsze oferty od artystów.' },
      { type: 'heading', level: 2, text: 'Krok 4: Otrzymaj oferty' },
      { type: 'paragraph', text: 'Zweryfikowani artyści składają formalne oferty z wyceną, terminem i zakresem prac. Porównaj portfolio, cenę i podejście każdego artysty.' },
      { type: 'heading', level: 2, text: 'Krok 5: Wybierz artystę' },
      { type: 'paragraph', text: 'Porównaj portfolio, cenę i opinie. Akceptuj ofertę, która najbardziej Ci odpowiada. Pamiętaj, że najtańsza oferta nie zawsze jest najlepsza - doświadczenie artysty ma znaczenie.' },
      { type: 'heading', level: 2, text: 'Krok 6: Realizacja i odbiór' },
      { type: 'paragraph', text: 'Płacisz zaliczkę (40%), artysta rozpoczyna pracę. Po ukończeniu akceptujesz obraz i płacisz pozostałe 60%. Cały proces jest bezpieczny i transparentny.' },
    ],
    author: 'Redakcja Artiors',
    category: 'jak-zamowic-obraz',
    tags: ['jak zlecić obraz', 'przewodnik', 'obrazy na zamówienie', 'zlecanie'],
    publishedAt: '2026-08-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
    noindex: false,
    schemaType: 'Article',
    readingTime: 8,
    status: 'published',
  },
  'ile-kosztuje-obraz-na-zamowienie': {
    id: 'fallback-2',
    slug: 'ile-kosztuje-obraz-na-zamowienie',
    title: 'Ile kosztuje obraz na zamówienie? Ceny i budżet',
    excerpt: 'Ceny obrazów ręcznie malowanych - co wpływa na wycenę i jak ustalić realistyczny budżet na obraz na zamówienie.',
    content: [
      { type: 'paragraph', text: 'Cena obrazu na zamówienie zależy od wielu czynników: wielkości, techniki, stylu, doświadczenia artysty, materiałów i terminu realizacji. W tym artykule wyjaśniamy, co wpływa na wycenę i jak ustalić realistyczny budżet.' },
      { type: 'heading', level: 2, text: 'Wielkość obrazu' },
      { type: 'paragraph', text: 'Większe obrazy wymagają więcej materiałów i czasu. Obraz 100×80 cm będzie kosztował więcej niż 50×40 cm, ale proporcja nie jest liniowa - duże płótna wymagają też innego podejścia kompozycyjnego.' },
      { type: 'heading', level: 2, text: 'Technika malarska' },
      { type: 'paragraph', text: 'Malarstwo olejne jest zazwyczaj droższe ze względu na koszt materiałów i dłuższy czas schnięcia. Akryl i akwarela mogą być tańsze, ale oferują inne możliwości wyrazu.' },
      { type: 'heading', level: 2, text: 'Doświadczenie artysty' },
      { type: 'paragraph', text: 'Artyści z większym doświadczeniem i rozpoznawalnością pobierają wyższe ceny. Na platformie znajdziesz artystów w różnych przedziałach cenowych.' },
      { type: 'heading', level: 2, text: 'Materiały i jakość' },
      { type: 'paragraph', text: 'Wysokiej jakości płótna, pigmenty i werniksy podnoszą cenę, ale też trwałość obrazu. Warto zapytać artystę o użyte materiały.' },
      { type: 'heading', level: 2, text: 'Termin realizacji' },
      { type: 'paragraph', text: 'Pilne zlecenia mogą kosztować więcej. Realistyczny termin (8-12 tygodni) zazwyczaj oznacza lepsze oferty.' },
      { type: 'heading', level: 2, text: 'Jak ustalić budżet?' },
      { type: 'paragraph', text: 'Na platformie ustalasz zakres cenowy, a artyści dopasowują ofertę do Twojego budżetu. Jeśli nie jesteś pewien, zacznij od szerszego zakresu - artysta może zasugerować optymalne rozwiązanie.' },
    ],
    author: 'Redakcja Artiors',
    category: 'obrazy-na-zamowienie',
    tags: ['cena obrazu', 'obrazy na zamówienie', 'budżet', 'wycena'],
    publishedAt: '2026-07-25T00:00:00Z',
    updatedAt: '2026-07-25T00:00:00Z',
    noindex: false,
    schemaType: 'Article',
    readingTime: 6,
    status: 'published',
  },
  'obraz-do-salonu-jak-wybrac': {
    id: 'fallback-3',
    slug: 'obraz-do-salonu-jak-wybrac',
    title: 'Obraz do salonu - jak wybrać idealny',
    excerpt: 'Skala, paleta, styl i kompozycja. Jak dopasować obraz do wnętrza salonu, aby stworzył spójną i harmonijną przestrzeń.',
    content: [
      { type: 'paragraph', text: 'Wybór obrazu do salonu to decyzja, która wpływa na całą przestrzeń. Oto kluczowe czynniki, które warto rozważyć, aby obraz stał się naturalnym centrum wnętrza.' },
      { type: 'heading', level: 2, text: 'Skala i proporcje' },
      { type: 'paragraph', text: 'Obraz powinien być proporcjonalny do ściany i mebli. Nad trójosobową kanapą najlepiej wygląda obraz o szerokości 2/3 szerokości kanapy. Zbyt mały obraz ginie, zbyt duży przytłacza.' },
      { type: 'heading', level: 2, text: 'Paleta kolorów' },
      { type: 'paragraph', text: 'Dobierz kolory obrazu do palety wnętrza. Możesz wybrać kolory uzupełniające lub kontrastowe. Obraz może też stać się akcentem kolorystycznym w stonowanym wnętrzu.' },
      { type: 'heading', level: 2, text: 'Styl obrazu' },
      { type: 'paragraph', text: 'Abstrakcja pasuje do nowoczesnych wnętrz, pejzaże do klasycznych, minimalizm do skandynawskich. Dopasuj styl obrazu do charakteru przestrzeni.' },
      { type: 'heading', level: 2, text: 'Kompozycja i orientacja' },
      { type: 'paragraph', text: 'Pozioma kompozycja do szerokich ścian, pionowa do wąskich, kwadratowa do małych przestrzeni. Zwróć uwagę na to, gdzie obraz będzie wisiał.' },
      { type: 'heading', level: 2, text: 'Oświetlenie' },
      { type: 'paragraph', text: 'Zwróć uwagę na naturalne i sztuczne światło - wpływa na odbiór kolorów. Obraz wieszany naprzeciwko okna może wyglądać inaczej niż w korytarzu ze sztucznym światłem.' },
    ],
    author: 'Redakcja Artiors',
    category: 'obrazy-do-wnetrz',
    tags: ['obraz do salonu', 'wnętrza', 'dobór obrazu', 'obrazy do wnętrz'],
    publishedAt: '2026-07-20T00:00:00Z',
    updatedAt: '2026-07-20T00:00:00Z',
    noindex: false,
    schemaType: 'Article',
    readingTime: 5,
    status: 'published',
  },
  'techniki-malarskie-olej-akryl': {
    id: 'fallback-4',
    slug: 'techniki-malarskie-olej-akryl',
    title: 'Techniki malarskie: olej vs akryl',
    excerpt: 'Różnice między malarstwem olejnym a akrylowym - który wybór jest lepszy dla Twojego obrazu na zamówienie?',
    content: [
      { type: 'paragraph', text: 'Olej i akryl to dwie najpopularniejsze techniki malarskie. Każda ma swoje zalety i wady, które wpływają na ostateczny wygląd i trwałość obrazu.' },
      { type: 'heading', level: 2, text: 'Malarstwo olejne' },
      { type: 'paragraph', text: 'Bogate kolory, długi czas schnięcia (tygodnie do miesięcy), możliwość mieszania i korygowania. Olej oferuje głębię koloru i gładkie przejścia tonalne. Wymaga rozpuszczalników i werniksu.' },
      { type: 'heading', level: 2, text: 'Malarstwo akrylowe' },
      { type: 'paragraph', text: 'Szybkie schnięcie (minuty do godziny), wodne rozcieńczalne, uniwersalne. Akryl można nakładać warstwowo, imitować olej lub akwarelę. Mniej intensywne kolory niż olej.' },
      { type: 'heading', level: 2, text: 'Którą technikę wybrać?' },
      { type: 'paragraph', text: 'Wybór zależy od stylu, terminu i budżetu. Na platformie artyści pracują w obu technikach - określ preferencję w zleceniu.' },
    ],
    author: 'Redakcja Artiors',
    category: 'style-malarskie',
    tags: ['techniki malarskie', 'olej', 'akryl', 'style malarskie'],
    publishedAt: '2026-07-15T00:00:00Z',
    updatedAt: '2026-07-15T00:00:00Z',
    noindex: false,
    schemaType: 'Article',
    readingTime: 7,
    status: 'published',
  },
  'portfolio-artysty-jak-zbudowac': {
    id: 'fallback-5',
    slug: 'portfolio-artysty-jak-zbudowac',
    title: 'Portfolio artysty - jak zbudować i prezentować prace',
    excerpt: 'Praktyczne porady dla artystów: jak prezentować prace, budować zaufanie zlecających i zwiększać szanse na otrzymanie zleceń.',
    content: [
      { type: 'paragraph', text: 'Portfolio to najważniejsze narzędzie artysty na platformie. Zlecający decydują na podstawie prac, które widzą. Oto jak zbudować portfolio, które buduje zaufanie i przyciąga zlecenia.' },
      { type: 'heading', level: 2, text: 'Wybór prac' },
      { type: 'paragraph', text: 'Pokaż 10-20 najlepszych prac. Jakość ponad ilość. Wybierz prace, które reprezentują Twój styl i technikę.' },
      { type: 'heading', level: 2, text: 'Zdjęcia prac' },
      { type: 'paragraph', text: 'Zadbaj o dobre oświetlenie i ostrość. Fotografuj obrazy w naturalnym świetle, bez odbić. Słabe zdjęcia mogą zniwelować jakość świetnej pracy.' },
      { type: 'heading', level: 2, text: 'Opisy i metadane' },
      { type: 'paragraph', text: 'Każda praca powinna mieć tytuł, technikę, wymiary i rok. Dodaj krótki opis koncepcji, który pokaże Twoje podejście twórcze.' },
      { type: 'heading', level: 2, text: 'Różnorodność i spójność' },
      { type: 'paragraph', text: 'Pokaż zakres - różne style, techniki, formaty. Ale zachowaj spójność stylistyczną, aby zlecający wiedział, czego się spodziewać.' },
    ],
    author: 'Redakcja Artiors',
    category: 'poradniki-dla-artystow',
    tags: ['portfolio', 'dla artystów', 'prezentacja prac', 'kariera artysty'],
    publishedAt: '2026-07-10T00:00:00Z',
    updatedAt: '2026-07-10T00:00:00Z',
    noindex: false,
    schemaType: 'Article',
    readingTime: 6,
    status: 'published',
  },
  'inspiracje-palety-kolorow': {
    id: 'fallback-6',
    slug: 'inspiracje-palety-kolorow',
    title: 'Inspiracje: palety kolorów na sezon',
    excerpt: 'Modne palety kolorów w malarstwie - od ciepłych ziemistych po chłodne minimalistyczne. Znajdź inspirację dla swojego obrazu.',
    content: [
      { type: 'paragraph', text: 'Kolory określają nastrój obrazu i jego relację z wnętrzem. Oto modne palety, które inspirują artystów i zlecających.' },
      { type: 'heading', level: 2, text: 'Ziemiste i naturalne' },
      { type: 'paragraph', text: 'Beże, ochry, terakoty, oliwkowe zielenie. Ciepłe, naturalne, kojące. Pasują do wnętrz japandi i boho.' },
      { type: 'heading', level: 2, text: 'Minimalistyczne' },
      { type: 'paragraph', text: 'Biel, szarości, czerń z akcentami. Spokojne, czyste, eleganckie. Idealne do nowoczesnych i skandynawskich wnętrz.' },
      { type: 'heading', level: 2, text: 'Jewel tones' },
      { type: 'paragraph', text: 'Szmaragd, granat, burgund, złoto. Bogate, luksusowe, dramatyczne. Pasują do klasycznych i glamour wnętrz.' },
      { type: 'heading', level: 2, text: 'Pastelowe' },
      { type: 'paragraph', text: 'Pudrowy róż, mięta, lawenda, błękit. Delikatne, romantyczne, spokojne. Idealne do sypialni i dziecięcych pokoi.' },
    ],
    author: 'Redakcja Artiors',
    category: 'obrazy-do-wnetrz',
    tags: ['palety kolorów', 'inspiracje', 'kolory', 'obrazy do wnętrz'],
    publishedAt: '2026-07-05T00:00:00Z',
    updatedAt: '2026-07-05T00:00:00Z',
    noindex: false,
    schemaType: 'Article',
    readingTime: 4,
    status: 'published',
  },
};

const SUMMARY_LIST: BlogPostSummary[] = Object.values(POSTS).map((p) => ({
  id: p.id,
  slug: p.slug,
  title: p.title,
  excerpt: p.excerpt,
  author: p.author,
  category: p.category,
  tags: p.tags,
  publishedAt: p.publishedAt,
  readingTime: p.readingTime,
}));

export function getStaticBlogPosts(): BlogPostSummary[] {
  return [...SUMMARY_LIST].sort((a, b) => b.publishedAt.localeCompare(a.publishedAt));
}

export function getStaticBlogPost(slug: string): BlogPost | null {
  return POSTS[slug] ?? null;
}
