/**
 * Sitemap management utilities.
 * The sitemap is served as a static index at /sitemap.xml pointing to
 * dynamic sub-sitemaps generated by the `sitemap` edge function, which
 * queries the database live on every request.
 *
 * The sub-sitemaps are accessible at:
 *   https://artiors.pl/sitemap-pages.xml
 *   https://artiors.pl/sitemap-artists.xml
 *   https://artiors.pl/sitemap-commissions.xml
 *   https://artiors.pl/sitemap-blog.xml
 *
 * These are proxied to the edge function via _redirects or edge config.
 */

const SITEMAP_INDEX_URL = 'https://artiors.pl/sitemap.xml';

export const SITEMAP_ENDPOINTS = {
  index: SITEMAP_INDEX_URL,
  pages: 'https://artiors.pl/sitemap-pages.xml',
  artists: 'https://artiors.pl/sitemap-artists.xml',
  commissions: 'https://artiors.pl/sitemap-commissions.xml',
  blog: 'https://artiors.pl/sitemap-blog.xml',
} as const;

/**
 * Ping search engines to notify them of sitemap updates.
 * Call this after publishing/unpublishing content (blog posts, artists, commissions).
 */
export async function pingSearchEngines(): Promise<{ google: boolean; bing: boolean }> {
  const encodedSitemap = encodeURIComponent(SITEMAP_INDEX_URL);

  const results = await Promise.allSettled([
    fetch(`https://www.google.com/ping?sitemap=${encodedSitemap}`, { method: 'GET' }),
    fetch(`https://www.bing.com/ping?sitemap=${encodedSitemap}`, { method: 'GET' }),
  ]);

  return {
    google: results[0].status === 'fulfilled' && results[0].value.ok,
    bing: results[1].status === 'fulfilled' && results[1].value.ok,
  };
}

/**
 * Verify that a sub-sitemap is accessible and returns valid XML.
 * Useful for admin diagnostics.
 */
export async function verifySitemap(
  type: 'pages' | 'artists' | 'commissions' | 'blog',
): Promise<{ ok: boolean; urlCount: number; error?: string }> {
  try {
    const response = await fetch(SITEMAP_ENDPOINTS[type]);
    if (!response.ok) {
      return { ok: false, urlCount: 0, error: `HTTP ${response.status}` };
    }
    const xml = await response.text();
    const urlCount = (xml.match(/<loc>/g) ?? []).length;
    return { ok: true, urlCount };
  } catch (err) {
    return {
      ok: false,
      urlCount: 0,
      error: err instanceof Error ? err.message : 'Unknown error',
    };
  }
}
